# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FediBooks/gui/wzd_createcondition.ui',
# licensing of 'FediBooks/gui/wzd_createcondition.ui' applies.
#
# Created: Sat Feb 23 11:55:35 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(633, 487)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
		self.verticalLayout.setSpacing(0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
		self.stackedWidget.setObjectName("stackedWidget")
		self.page_2 = QtWidgets.QWidget()
		self.page_2.setObjectName("page_2")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.label_4 = QtWidgets.QLabel(self.page_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
		self.label_4.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(24)
		self.label_4.setFont(font)
		self.label_4.setTextFormat(QtCore.Qt.AutoText)
		self.label_4.setScaledContents(True)
		self.label_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.label_4.setObjectName("label_4")
		self.verticalLayout_3.addWidget(self.label_4)
		self.label_3 = QtWidgets.QLabel(self.page_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
		self.label_3.setSizePolicy(sizePolicy)
		self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
		self.label_3.setWordWrap(True)
		self.label_3.setObjectName("label_3")
		self.verticalLayout_3.addWidget(self.label_3)
		self.tabWidget = QtWidgets.QTabWidget(self.page_2)
		self.tabWidget.setObjectName("tabWidget")
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName("tab")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.lineEdit = QtWidgets.QLineEdit(self.tab)
		self.lineEdit.setObjectName("lineEdit")
		self.verticalLayout_4.addWidget(self.lineEdit)
		self.checkBox = QtWidgets.QCheckBox(self.tab)
		self.checkBox.setObjectName("checkBox")
		self.verticalLayout_4.addWidget(self.checkBox)
		self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
		self.checkBox_2.setObjectName("checkBox_2")
		self.verticalLayout_4.addWidget(self.checkBox_2)
		spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_4.addItem(spacerItem)
		self.tabWidget.addTab(self.tab, "")
		self.tab_2 = QtWidgets.QWidget()
		self.tab_2.setObjectName("tab_2")
		self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
		self.lineEdit_2.setObjectName("lineEdit_2")
		self.verticalLayout_5.addWidget(self.lineEdit_2)
		self.checkBox_3 = QtWidgets.QCheckBox(self.tab_2)
		self.checkBox_3.setObjectName("checkBox_3")
		self.verticalLayout_5.addWidget(self.checkBox_3)
		self.checkBox_4 = QtWidgets.QCheckBox(self.tab_2)
		self.checkBox_4.setObjectName("checkBox_4")
		self.verticalLayout_5.addWidget(self.checkBox_4)
		spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_5.addItem(spacerItem1)
		self.tabWidget.addTab(self.tab_2, "")
		self.tab_3 = QtWidgets.QWidget()
		self.tab_3.setObjectName("tab_3")
		self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.label_7 = QtWidgets.QLabel(self.tab_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
		self.label_7.setSizePolicy(sizePolicy)
		self.label_7.setObjectName("label_7")
		self.horizontalLayout.addWidget(self.label_7)
		self.timeEdit = QtWidgets.QTimeEdit(self.tab_3)
		self.timeEdit.setObjectName("timeEdit")
		self.horizontalLayout.addWidget(self.timeEdit)
		self.label_8 = QtWidgets.QLabel(self.tab_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
		self.label_8.setSizePolicy(sizePolicy)
		self.label_8.setObjectName("label_8")
		self.horizontalLayout.addWidget(self.label_8)
		self.timeEdit_2 = QtWidgets.QTimeEdit(self.tab_3)
		self.timeEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(12, 0, 0)))
		self.timeEdit_2.setObjectName("timeEdit_2")
		self.horizontalLayout.addWidget(self.timeEdit_2)
		spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem2)
		self.verticalLayout_6.addLayout(self.horizontalLayout)
		spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_6.addItem(spacerItem3)
		self.tabWidget.addTab(self.tab_3, "")
		self.tab_4 = QtWidgets.QWidget()
		self.tab_4.setObjectName("tab_4")
		self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_4)
		self.verticalLayout_10.setObjectName("verticalLayout_10")
		self.gridLayout = QtWidgets.QGridLayout()
		self.gridLayout.setObjectName("gridLayout")
		self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_4)
		self.lineEdit_5.setObjectName("lineEdit_5")
		self.gridLayout.addWidget(self.lineEdit_5, 1, 2, 1, 1)
		self.label_6 = QtWidgets.QLabel(self.tab_4)
		self.label_6.setObjectName("label_6")
		self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
		self.comboBox_2 = QtWidgets.QComboBox(self.tab_4)
		self.comboBox_2.setMinimumSize(QtCore.QSize(100, 0))
		self.comboBox_2.setObjectName("comboBox_2")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.gridLayout.addWidget(self.comboBox_2, 1, 1, 1, 1)
		self.label_5 = QtWidgets.QLabel(self.tab_4)
		self.label_5.setObjectName("label_5")
		self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
		self.comboBox = QtWidgets.QComboBox(self.tab_4)
		self.comboBox.setMinimumSize(QtCore.QSize(100, 0))
		self.comboBox.setObjectName("comboBox")
		self.comboBox.addItem("")
		self.comboBox.addItem("")
		self.comboBox.addItem("")
		self.comboBox.addItem("")
		self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
		self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_4)
		self.lineEdit_4.setObjectName("lineEdit_4")
		self.gridLayout.addWidget(self.lineEdit_4, 0, 2, 1, 1)
		self.verticalLayout_10.addLayout(self.gridLayout)
		spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_10.addItem(spacerItem4)
		self.tabWidget.addTab(self.tab_4, "")
		self.tab_5 = QtWidgets.QWidget()
		self.tab_5.setObjectName("tab_5")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_5)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.label_11 = QtWidgets.QLabel(self.tab_5)
		self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
		self.label_11.setObjectName("label_11")
		self.horizontalLayout_2.addWidget(self.label_11)
		self.tabWidget.addTab(self.tab_5, "")
		self.verticalLayout_3.addWidget(self.tabWidget)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.lineEdit_3 = QtWidgets.QLineEdit(self.page_2)
		self.lineEdit_3.setClearButtonEnabled(True)
		self.lineEdit_3.setObjectName("lineEdit_3")
		self.horizontalLayout_3.addWidget(self.lineEdit_3)
		self.checkBox_5 = QtWidgets.QCheckBox(self.page_2)
		self.checkBox_5.setObjectName("checkBox_5")
		self.horizontalLayout_3.addWidget(self.checkBox_5)
		self.verticalLayout_3.addLayout(self.horizontalLayout_3)
		spacerItem5 = QtWidgets.QSpacerItem(20, 36, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_3.addItem(spacerItem5)
		self.stackedWidget.addWidget(self.page_2)
		self.page_5 = QtWidgets.QWidget()
		self.page_5.setObjectName("page_5")
		self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.page_5)
		self.verticalLayout_19.setObjectName("verticalLayout_19")
		self.label_24 = QtWidgets.QLabel(self.page_5)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
		self.label_24.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(24)
		self.label_24.setFont(font)
		self.label_24.setTextFormat(QtCore.Qt.AutoText)
		self.label_24.setScaledContents(True)
		self.label_24.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.label_24.setObjectName("label_24")
		self.verticalLayout_19.addWidget(self.label_24)
		self.label_25 = QtWidgets.QLabel(self.page_5)
		self.label_25.setWordWrap(True)
		self.label_25.setObjectName("label_25")
		self.verticalLayout_19.addWidget(self.label_25)
		self.lineEdit_12 = QtWidgets.QLineEdit(self.page_5)
		self.lineEdit_12.setPlaceholderText("")
		self.lineEdit_12.setClearButtonEnabled(True)
		self.lineEdit_12.setObjectName("lineEdit_12")
		self.verticalLayout_19.addWidget(self.lineEdit_12)
		spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_19.addItem(spacerItem6)
		self.stackedWidget.addWidget(self.page_5)
		self.page_4 = QtWidgets.QWidget()
		self.page_4.setObjectName("page_4")
		self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page_4)
		self.verticalLayout_18.setObjectName("verticalLayout_18")
		self.label_22 = QtWidgets.QLabel(self.page_4)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
		self.label_22.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(24)
		self.label_22.setFont(font)
		self.label_22.setTextFormat(QtCore.Qt.AutoText)
		self.label_22.setScaledContents(True)
		self.label_22.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.label_22.setObjectName("label_22")
		self.verticalLayout_18.addWidget(self.label_22)
		self.label_23 = QtWidgets.QLabel(self.page_4)
		self.label_23.setObjectName("label_23")
		self.verticalLayout_18.addWidget(self.label_23)
		self.checkBox_11 = QtWidgets.QCheckBox(self.page_4)
		self.checkBox_11.setCheckable(True)
		self.checkBox_11.setChecked(True)
		self.checkBox_11.setObjectName("checkBox_11")
		self.verticalLayout_18.addWidget(self.checkBox_11)
		spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_18.addItem(spacerItem7)
		self.stackedWidget.addWidget(self.page_4)
		self.verticalLayout.addWidget(self.stackedWidget)
		self.hbx_button_box = QtWidgets.QHBoxLayout()
		self.hbx_button_box.setObjectName("hbx_button_box")
		self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("."), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.btn_cancel.setIcon(icon)
		self.btn_cancel.setObjectName("btn_cancel")
		self.hbx_button_box.addWidget(self.btn_cancel)
		self.btn_help = QtWidgets.QPushButton(self.centralwidget)
		self.btn_help.setIcon(icon)
		self.btn_help.setObjectName("btn_help")
		self.hbx_button_box.addWidget(self.btn_help)
		spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.hbx_button_box.addItem(spacerItem8)
		self.btn_back = QtWidgets.QPushButton(self.centralwidget)
		self.btn_back.setIcon(icon)
		self.btn_back.setObjectName("btn_back")
		self.hbx_button_box.addWidget(self.btn_back)
		self.btn_next = QtWidgets.QPushButton(self.centralwidget)
		self.btn_next.setIcon(icon)
		self.btn_next.setAutoDefault(True)
		self.btn_next.setDefault(True)
		self.btn_next.setObjectName("btn_next")
		self.hbx_button_box.addWidget(self.btn_next)
		self.verticalLayout.addLayout(self.hbx_button_box)
		MainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(MainWindow)
		self.stackedWidget.setCurrentIndex(0)
		self.tabWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Rule Creation Wizard", None, -1))
		self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Create Condition", None, -1))
		self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Conditions</span> are what the bot checks for before activating this rule. For example, you might have a rule that says &quot;add an exclamation mark&quot; that is activated when a post meets the <span style=\" font-weight:600;\">condition</span> of containing the word &quot;pop&quot;. Rulesets can have more than one condition.</p><p>Once you\'ve selected a condition type, click <span style=\" font-weight:600;\">Next</span>.</p></body></html>", None, -1))
		self.lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Hello", None, -1))
		self.checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "Case sensitive", None, -1))
		self.checkBox_2.setText(QtWidgets.QApplication.translate("MainWindow", "Also match if it\'s part of another word", None, -1))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Content match", None, -1))
		self.lineEdit_2.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "[Rr]eg(ular +)?[Ee]x(?:pression)?", None, -1))
		self.checkBox_3.setText(QtWidgets.QApplication.translate("MainWindow", "Case sensitive", None, -1))
		self.checkBox_4.setText(QtWidgets.QApplication.translate("MainWindow", "Multiline", None, -1))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "RegEx Match", None, -1))
		self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Between", None, -1))
		self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "and", None, -1))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "Time and Date", None, -1))
		self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "from", None, -1))
		self.comboBox_2.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "any username", None, -1))
		self.comboBox_2.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "username containing", None, -1))
		self.comboBox_2.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "username exactly matching", None, -1))
		self.comboBox_2.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "username matching (RegEx)", None, -1))
		self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Reply comes from", None, -1))
		self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "any instance", None, -1))
		self.comboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "instance containing", None, -1))
		self.comboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "instance exactly matching", None, -1))
		self.comboBox.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "intance matching (RegEx)", None, -1))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("MainWindow", "Reply source", None, -1))
		self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "This condition is always true. Use this to create a default ruleset.", None, -1))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtWidgets.QApplication.translate("MainWindow", "Global", None, -1))
		self.lineEdit_3.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Enter text to test the condition against here", None, -1))
		self.checkBox_5.setText(QtWidgets.QApplication.translate("MainWindow", "Match", None, -1))
		self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Set Condition Name", None, -1))
		self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>If you wish, you may enter a descriptive name for your rule below. Click <span style=\" font-weight:600;\">Next</span> when you\'re ready to continue.</p></body></html>", None, -1))
		self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Done!", None, -1))
		self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Your condition has been created and is ready to be enabled.", None, -1))
		self.checkBox_11.setText(QtWidgets.QApplication.translate("MainWindow", "Enable condition now", None, -1))
		self.btn_cancel.setText(QtWidgets.QApplication.translate("MainWindow", "&Cancel", None, -1))
		self.btn_help.setText(QtWidgets.QApplication.translate("MainWindow", "&Help", None, -1))
		self.btn_back.setText(QtWidgets.QApplication.translate("MainWindow", "&Back", None, -1))
		self.btn_next.setText(QtWidgets.QApplication.translate("MainWindow", "&Next", None, -1))

