# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FediBooks/gui/wzd_createaction.ui',
# licensing of 'FediBooks/gui/wzd_createaction.ui' applies.
#
# Created: Sat Feb 23 11:55:35 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(633, 487)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
		self.verticalLayout.setSpacing(0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
		self.stackedWidget.setObjectName("stackedWidget")
		self.page_3 = QtWidgets.QWidget()
		self.page_3.setObjectName("page_3")
		self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_3)
		self.verticalLayout_12.setObjectName("verticalLayout_12")
		self.label_9 = QtWidgets.QLabel(self.page_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
		self.label_9.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(24)
		self.label_9.setFont(font)
		self.label_9.setTextFormat(QtCore.Qt.AutoText)
		self.label_9.setScaledContents(True)
		self.label_9.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.label_9.setObjectName("label_9")
		self.verticalLayout_12.addWidget(self.label_9)
		self.label_10 = QtWidgets.QLabel(self.page_3)
		self.label_10.setWordWrap(True)
		self.label_10.setObjectName("label_10")
		self.verticalLayout_12.addWidget(self.label_10)
		self.tabWidget_2 = QtWidgets.QTabWidget(self.page_3)
		self.tabWidget_2.setObjectName("tabWidget_2")
		self.tab_6 = QtWidgets.QWidget()
		self.tab_6.setObjectName("tab_6")
		self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_6)
		self.verticalLayout_14.setObjectName("verticalLayout_14")
		self.label_27 = QtWidgets.QLabel(self.tab_6)
		self.label_27.setWordWrap(True)
		self.label_27.setObjectName("label_27")
		self.verticalLayout_14.addWidget(self.label_27)
		self.gridLayout_3 = QtWidgets.QGridLayout()
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_6)
		self.lineEdit_8.setObjectName("lineEdit_8")
		self.gridLayout_3.addWidget(self.lineEdit_8, 0, 1, 1, 1)
		self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_6)
		self.lineEdit_9.setObjectName("lineEdit_9")
		self.gridLayout_3.addWidget(self.lineEdit_9, 1, 1, 1, 1)
		self.label_15 = QtWidgets.QLabel(self.tab_6)
		self.label_15.setObjectName("label_15")
		self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
		self.label_16 = QtWidgets.QLabel(self.tab_6)
		self.label_16.setObjectName("label_16")
		self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
		self.verticalLayout_14.addLayout(self.gridLayout_3)
		self.checkBox_8 = QtWidgets.QCheckBox(self.tab_6)
		self.checkBox_8.setObjectName("checkBox_8")
		self.verticalLayout_14.addWidget(self.checkBox_8)
		self.checkBox_9 = QtWidgets.QCheckBox(self.tab_6)
		self.checkBox_9.setObjectName("checkBox_9")
		self.verticalLayout_14.addWidget(self.checkBox_9)
		spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_14.addItem(spacerItem)
		self.tabWidget_2.addTab(self.tab_6, "")
		self.tab_7 = QtWidgets.QWidget()
		self.tab_7.setObjectName("tab_7")
		self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_7)
		self.verticalLayout_13.setObjectName("verticalLayout_13")
		self.label_28 = QtWidgets.QLabel(self.tab_7)
		self.label_28.setWordWrap(True)
		self.label_28.setObjectName("label_28")
		self.verticalLayout_13.addWidget(self.label_28)
		self.gridLayout_2 = QtWidgets.QGridLayout()
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_7)
		self.lineEdit_6.setObjectName("lineEdit_6")
		self.gridLayout_2.addWidget(self.lineEdit_6, 0, 1, 1, 1)
		self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_7)
		self.lineEdit_7.setObjectName("lineEdit_7")
		self.gridLayout_2.addWidget(self.lineEdit_7, 1, 1, 1, 1)
		self.label_13 = QtWidgets.QLabel(self.tab_7)
		self.label_13.setObjectName("label_13")
		self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
		self.label_14 = QtWidgets.QLabel(self.tab_7)
		self.label_14.setObjectName("label_14")
		self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
		self.verticalLayout_13.addLayout(self.gridLayout_2)
		self.checkBox_6 = QtWidgets.QCheckBox(self.tab_7)
		self.checkBox_6.setObjectName("checkBox_6")
		self.verticalLayout_13.addWidget(self.checkBox_6)
		self.checkBox_7 = QtWidgets.QCheckBox(self.tab_7)
		self.checkBox_7.setObjectName("checkBox_7")
		self.verticalLayout_13.addWidget(self.checkBox_7)
		self.label_12 = QtWidgets.QLabel(self.tab_7)
		self.label_12.setObjectName("label_12")
		self.verticalLayout_13.addWidget(self.label_12)
		spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_13.addItem(spacerItem1)
		self.tabWidget_2.addTab(self.tab_7, "")
		self.tab_8 = QtWidgets.QWidget()
		self.tab_8.setObjectName("tab_8")
		self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_8)
		self.verticalLayout_15.setObjectName("verticalLayout_15")
		self.label_17 = QtWidgets.QLabel(self.tab_8)
		self.label_17.setObjectName("label_17")
		self.verticalLayout_15.addWidget(self.label_17)
		self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_8)
		self.lineEdit_10.setObjectName("lineEdit_10")
		self.verticalLayout_15.addWidget(self.lineEdit_10)
		spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_15.addItem(spacerItem2)
		self.tabWidget_2.addTab(self.tab_8, "")
		self.tab_9 = QtWidgets.QWidget()
		self.tab_9.setObjectName("tab_9")
		self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_9)
		self.verticalLayout_17.setObjectName("verticalLayout_17")
		self.label_19 = QtWidgets.QLabel(self.tab_9)
		self.label_19.setWordWrap(True)
		self.label_19.setObjectName("label_19")
		self.verticalLayout_17.addWidget(self.label_19)
		self.label_20 = QtWidgets.QLabel(self.tab_9)
		self.label_20.setObjectName("label_20")
		self.verticalLayout_17.addWidget(self.label_20)
		self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_9)
		self.lineEdit_11.setObjectName("lineEdit_11")
		self.verticalLayout_17.addWidget(self.lineEdit_11)
		self.checkBox_10 = QtWidgets.QCheckBox(self.tab_9)
		self.checkBox_10.setObjectName("checkBox_10")
		self.verticalLayout_17.addWidget(self.checkBox_10)
		self.label_21 = QtWidgets.QLabel(self.tab_9)
		self.label_21.setObjectName("label_21")
		self.verticalLayout_17.addWidget(self.label_21)
		self.comboBox_3 = QtWidgets.QComboBox(self.tab_9)
		self.comboBox_3.setObjectName("comboBox_3")
		self.comboBox_3.addItem("")
		self.comboBox_3.addItem("")
		self.comboBox_3.addItem("")
		self.comboBox_3.addItem("")
		self.verticalLayout_17.addWidget(self.comboBox_3)
		spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_17.addItem(spacerItem3)
		self.tabWidget_2.addTab(self.tab_9, "")
		self.tab_10 = QtWidgets.QWidget()
		self.tab_10.setObjectName("tab_10")
		self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_10)
		self.verticalLayout_16.setObjectName("verticalLayout_16")
		self.label_18 = QtWidgets.QLabel(self.tab_10)
		self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
		self.label_18.setWordWrap(True)
		self.label_18.setObjectName("label_18")
		self.verticalLayout_16.addWidget(self.label_18)
		self.tabWidget_2.addTab(self.tab_10, "")
		self.verticalLayout_12.addWidget(self.tabWidget_2)
		self.stackedWidget.addWidget(self.page_3)
		self.page_5 = QtWidgets.QWidget()
		self.page_5.setObjectName("page_5")
		self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.page_5)
		self.verticalLayout_19.setObjectName("verticalLayout_19")
		self.label_24 = QtWidgets.QLabel(self.page_5)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
		self.label_24.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(24)
		self.label_24.setFont(font)
		self.label_24.setTextFormat(QtCore.Qt.AutoText)
		self.label_24.setScaledContents(True)
		self.label_24.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.label_24.setObjectName("label_24")
		self.verticalLayout_19.addWidget(self.label_24)
		self.label_25 = QtWidgets.QLabel(self.page_5)
		self.label_25.setObjectName("label_25")
		self.verticalLayout_19.addWidget(self.label_25)
		self.lineEdit_12 = QtWidgets.QLineEdit(self.page_5)
		self.lineEdit_12.setObjectName("lineEdit_12")
		self.verticalLayout_19.addWidget(self.lineEdit_12)
		spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_19.addItem(spacerItem4)
		self.stackedWidget.addWidget(self.page_5)
		self.page_4 = QtWidgets.QWidget()
		self.page_4.setObjectName("page_4")
		self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page_4)
		self.verticalLayout_18.setObjectName("verticalLayout_18")
		self.label_22 = QtWidgets.QLabel(self.page_4)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
		self.label_22.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(24)
		self.label_22.setFont(font)
		self.label_22.setTextFormat(QtCore.Qt.AutoText)
		self.label_22.setScaledContents(True)
		self.label_22.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.label_22.setObjectName("label_22")
		self.verticalLayout_18.addWidget(self.label_22)
		self.label_23 = QtWidgets.QLabel(self.page_4)
		self.label_23.setObjectName("label_23")
		self.verticalLayout_18.addWidget(self.label_23)
		self.checkBox_11 = QtWidgets.QCheckBox(self.page_4)
		self.checkBox_11.setObjectName("checkBox_11")
		self.verticalLayout_18.addWidget(self.checkBox_11)
		spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_18.addItem(spacerItem5)
		self.stackedWidget.addWidget(self.page_4)
		self.verticalLayout.addWidget(self.stackedWidget)
		self.hbx_button_box = QtWidgets.QHBoxLayout()
		self.hbx_button_box.setObjectName("hbx_button_box")
		self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("."), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.btn_cancel.setIcon(icon)
		self.btn_cancel.setObjectName("btn_cancel")
		self.hbx_button_box.addWidget(self.btn_cancel)
		self.btn_help = QtWidgets.QPushButton(self.centralwidget)
		self.btn_help.setIcon(icon)
		self.btn_help.setObjectName("btn_help")
		self.hbx_button_box.addWidget(self.btn_help)
		spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.hbx_button_box.addItem(spacerItem6)
		self.btn_back = QtWidgets.QPushButton(self.centralwidget)
		self.btn_back.setIcon(icon)
		self.btn_back.setObjectName("btn_back")
		self.hbx_button_box.addWidget(self.btn_back)
		self.btn_next = QtWidgets.QPushButton(self.centralwidget)
		self.btn_next.setIcon(icon)
		self.btn_next.setAutoDefault(True)
		self.btn_next.setDefault(True)
		self.btn_next.setObjectName("btn_next")
		self.hbx_button_box.addWidget(self.btn_next)
		self.verticalLayout.addLayout(self.hbx_button_box)
		MainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(MainWindow)
		self.stackedWidget.setCurrentIndex(0)
		self.tabWidget_2.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Action Creation Wizard", None, -1))
		self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Select Action", None, -1))
		self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Your bot now needs <span style=\" font-weight:600;\">actions</span> to perform after the <span style=\" font-weight:600;\">conditions</span> are met. This can be anything from posting a custom message, modifying text, or even not posting at all.</p></body></html>", None, -1))
		self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Copy the text of the mention, replace all occurrences of the first item with the second, and reply with that.", None, -1))
		self.lineEdit_8.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "sad", None, -1))
		self.lineEdit_9.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "happy", None, -1))
		self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Find", None, -1))
		self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Replace with", None, -1))
		self.checkBox_8.setText(QtWidgets.QApplication.translate("MainWindow", "Case sensitive", None, -1))
		self.checkBox_9.setText(QtWidgets.QApplication.translate("MainWindow", "Multiline", None, -1))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QtWidgets.QApplication.translate("MainWindow", "Find and Replace", None, -1))
		self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Copy the text of the mention, run the provided RegEx find and replace on it, then reply with that.</p></body></html>", None, -1))
		self.lineEdit_6.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "My name is (.*)", None, -1))
		self.lineEdit_7.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Hello, \\1", None, -1))
		self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Find", None, -1))
		self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Replace with", None, -1))
		self.checkBox_6.setText(QtWidgets.QApplication.translate("MainWindow", "Case sensitive", None, -1))
		self.checkBox_7.setText(QtWidgets.QApplication.translate("MainWindow", "Multiline", None, -1))
		self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Capture groups used in the previous step can be accessed here.", None, -1))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QtWidgets.QApplication.translate("MainWindow", "RegEx", None, -1))
		self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Overwrite generated post with", None, -1))
		self.lineEdit_10.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "I\'m sorry, Dave. I\'m afraid I can\'t toot that.", None, -1))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QtWidgets.QApplication.translate("MainWindow", "Specify content", None, -1))
		self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Use this option with extreme caution.</span> The command will be run as the current user from the current directory. <span style=\" font-weight:600;\">This option can be very dangerous if used improperly.</span></p></body></html>", None, -1))
		self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Run this command:", None, -1))
		self.lineEdit_11.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "echo \"Hello there!\"", None, -1))
		self.checkBox_10.setText(QtWidgets.QApplication.translate("MainWindow", "Post the output (stdout)", None, -1))
		self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "In case of error (non-zero exit code):", None, -1))
		self.comboBox_3.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Post stdout", None, -1))
		self.comboBox_3.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Post stderr", None, -1))
		self.comboBox_3.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Post an error message", None, -1))
		self.comboBox_3.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "Don\'t post anything", None, -1))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), QtWidgets.QApplication.translate("MainWindow", "Run command", None, -1))
		self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "If you choose this option, your bot won\'t post at all if a post meets the specified conditions. It will not create a new post to use instead. If your bot posts every 30 minutes, it won\'t post for another 30 minutes, for example. Use this option with caution -- you probably don\'t want this.", None, -1))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), QtWidgets.QApplication.translate("MainWindow", "Don\'t post", None, -1))
		self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Set Action Name", None, -1))
		self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Enter a descriptive name for your rule below, then click <span style=\" font-weight:600;\">Next</span> to continue.</p></body></html>", None, -1))
		self.lineEdit_12.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Ignore posts by @jerk@bad.website", None, -1))
		self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Done!", None, -1))
		self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Your rule has been created and is ready to be enabled.", None, -1))
		self.checkBox_11.setText(QtWidgets.QApplication.translate("MainWindow", "Enable rule now", None, -1))
		self.btn_cancel.setText(QtWidgets.QApplication.translate("MainWindow", "&Cancel", None, -1))
		self.btn_help.setText(QtWidgets.QApplication.translate("MainWindow", "&Help", None, -1))
		self.btn_back.setText(QtWidgets.QApplication.translate("MainWindow", "&Back", None, -1))
		self.btn_next.setText(QtWidgets.QApplication.translate("MainWindow", "&Next", None, -1))

